test: &default

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for REST APIs
  client_id: <%= ENV["paypal_client_id"] %>
  client_secret: <%= ENV["paypal_client_secret"] %>

  # OpenID
  openid_client_id: <%= ENV["paypal_client_id"] %>
  openid_client_secret: <%= ENV["paypal_client_secret"] %>
  openid_redirect_uri: <%= ENV["paypal_redirect_uri"] %>

  # Sandbox Account
  sandbox_email_address: <%= ENV["paypal_email_address"] %>

development:
  <<: *default

production:
  <<: *default
  # mode: live
  mode: sandbox
